export const SPLASH_SCREEN = 'SplashScreen'
export const LOGIN_SCREEN = 'LoginScreen'
export const REGISTER_SCREEN = 'RegisterScreen'
export const HOME_SCREEN = 'HomeScreen'
export const CREATE_POST_SCREEN = 'CreatePostScreen'
export const COMMENT_SCREEN = 'CommentScreen'
export const EDIT_PROFILE_SCREEN = 'EditProfileScreen'
export const OTHER_USER_PROFILE_SCREEN = 'OtherUserProfileScreen'